### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by xuweisen** [aginev/datagrid#1]
Hi,

I'm using this datagrid, and setting it the same with your example. But the filter and sort it's not working. But when I search or sort, the link will change into http://localhost/17fit_studio/webadmin/rights?f%5Border_by%5D=role_id&f%5Border_dir%5D=DESC&page=1 But the data not change..
Can you help me?

$functions = WebAdmin::all();
$grid = new \Datagrid($functions, Request::get('f', []));

thanks

**Comment by aginev** [comment]
Hello,

The main purpose of this package is to build a table with your data with filters and order. You need to pass a collection of filtered results to it. You need to filter your $functions before to pass them to Datagrid.

Regards

Nasko

**Comment by aginev** [comment]
@xuweisen take a look here if still interested https://github.com/aginev/search-filters
