### ISSUE TITLE
Error on chaining properties

### ISSUE THREAD

**Issue by spernica** [aginev/datagrid#10]
When you have variable like $client->country->region->title and country is null, there is an error in ModelRow.php with undefined property. Right behavior of grid is to print just empty string "".

Your code is:

		// The easiest way to chain the object properties
		foreach ($keys as $key) {
			$value = $value->{$key};
		}

The right code is:

		// The easiest way to chain the object properties
		foreach ($keys as $key) {
			$value = $value->{$key};

			if (is_null($value)) {
				break;
			}
		}

Please apply that to your code

**Comment by aginev** [comment]
OK so fixed the issue but a bit differently just because if you just break the loop you'll return the parent object at the end. See: https://github.com/aginev/datagrid/commit/9f3fef53fe46d014727baeb015820f3a41225657

**Comment by spernica** [comment]
I understand why did you do that, but I think it would be my solution.

Let's say you have this structure:
Person - Country - City
Norman - France - Paris
Ema  - NULL - NULL

For Norman - it's ok.
For Ema - it's also okay, that she hasn't got city and you don't want to fire Exception.
