### ISSUE TITLE
Wrapper - empty returns always true

### ISSUE THREAD

**Issue by spernica** [aginev/datagrid#11]
This is very strange behavior. Empty condition is always true even if variable is for example 5.

    'wrapper' => function ($value, $row) {
        if (empty($row->created_by)) {
            return '';
	}

This works fine
    
     'wrapper' => function ($value, $row) {
	   if ( ! $row->created_by) {
		return '';
           }

**Comment by aginev** [comment]
https://stackoverflow.com/questions/3060420/empty-returning-true-on-objects-non-empty-property
