### ISSUE TITLE
Sorting and Filteration is not working with Laravel 5.7

### ISSUE THREAD

**Issue by matrixinfologics** [aginev/datagrid#17]
I am using this package in larave 5.7. 

Sorting and filteration is not working.

**Comment by aginev** [comment]
Sorting and filtering is not the point of this package. It only displays the table with filtering fields and sorting links. If you want sorting and filtering to work you should make it at your own in controller/model. In addition you can check https://github.com/aginev/search-filters that could help but again will not do automatically for you.

```
$orderProducts = $model->filter($request->input('f', []))->paginate(Pagination::getPerPage());
$grid = new \Datagrid($orderProducts, $request->input('f'));
...
```
