### ISSUE TITLE
its displaying as raw text only

### ISSUE THREAD

**Issue by snowwhite686** [aginev/datagrid#7]
{!! $grid->show('grid-table') !!}

not working , 

updated dependecies for laravelcollective/html , but no hope
![capture_adminpic](https://cloud.githubusercontent.com/assets/3541070/18585739/5ba4a538-7c36-11e6-94b6-774fc498ba2d.JPG)

please help,.

**Comment by aginev** [comment]
@snowwhite686 yes it injects HTML into your views. Give a bit more details...

**Comment by snowwhite686** [comment]
please check these [files](https://drive.google.com/open?id=0B4hLiOu9a0MIODZMMEZZMzNGcVE)
I am desperately trying to make this work..(#am a newbie to laravel), not sure am i missing something.
Please help me further, thank you for your support.
