### ISSUE TITLE
Any chance of seeing a demo of this?

### ISSUE THREAD

**Issue by bretto36** [aginev/datagrid#8]
Do you have a demo site anywhere that you can show

**Comment by aginev** [comment]
Hello, 

This is the only demo I can offer for now

https://youtu.be/Ka5yPXj7y5Y

Keep in mind that this package DOES NOT make the filter query for you. It just shows your data in table and adds filter and sort rows on top.

I have another package that adds necessary constraints to a Laravel model and works perfectly fine with the datagrid. You can check it here: https://github.com/aginev/search-filters

Regards 

Nasko
