### ISSUE TITLE
Allow HTML titles

### ISSUE THREAD

**Issue by taronarm** [aginev/datagrid#9]
It is not possible to set **HTML title** for **non-sortable** columns:
`->setColumn('name', '<strong>Name</strong>')`.
For sortable columns everything is OK.

> How to fix

Change **Views/grid.blade.php _line 28_** from `{{ $col->getTitle() }}` to `{!! $col->getTitle() !!}`

**Comment by aginev** [comment]
Thanks, this will be a good improvement, but next time consider submitting a pull request :). Already released a new version with your suggestion.

**Comment by taronarm** [comment]
Thank you for quick response :)
